"""Add learning system tables

Revision ID: 1af2fbfecaa1
Revises: e2366f4c3892
Create Date: 2025-08-12 02:44:34.047486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af2fbfecaa1'
down_revision = 'e2366f4c3892'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###