"""Add account number and card details to accounts table

Revision ID: 342bc809d12c
Revises: 7bc153c03aa1
Create Date: 2025-08-20 03:10:46.161238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342bc809d12c'
down_revision = '7bc153c03aa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_number', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('card_number', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('card_expiry_month', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('card_expiry_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'card_expiry_year')
    op.drop_column('accounts', 'card_expiry_month')
    op.drop_column('accounts', 'card_number')
    op.drop_column('accounts', 'account_number')
    # ### end Alembic commands ###