"""Add balance_after_transaction fields to transactions table

Revision ID: 7bc153c03aa1
Revises: c6daeabca098
Create Date: 2025-08-17 10:44:21.387088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc153c03aa1'
down_revision = 'c6daeabca098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('balance_after_transaction', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('to_account_balance_after', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'to_account_balance_after')
    op.drop_column('transactions', 'balance_after_transaction')
    # ### end Alembic commands ###