"""Add PPF account type and interest rate field

Revision ID: 846486f8bdb8
Revises: 342bc809d12c
Create Date: 2025-09-03 07:35:12.803132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846486f8bdb8'
down_revision = '342bc809d12c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'interest_rate')
    # ### end Alembic commands ###