"""Add color field to payees table

Revision ID: c6daeabca098
Revises: 1af2fbfecaa1
Create Date: 2025-08-13 17:05:06.657213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6daeabca098'
down_revision = '1af2fbfecaa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payees', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payees', 'color')
    # ### end Alembic commands ###