"""Add transaction splits table

Revision ID: cd20f777daba
Revises: b31578fb75e3
Create Date: 2025-09-10 11:11:54.111001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd20f777daba'
down_revision = 'b31578fb75e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###